-- Script DDL da trilha (estrutura)
-- Objetivo: criar tabela de clientes com regras minimas de integridade.

CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(120) NOT NULL,
    email VARCHAR2(160) NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE NOT NULL
);

-- Explicacao:
-- id: chave primaria unica, gerada pelo banco.
-- nome/email: obrigatorios.
-- data_cadastro: default para data atual se nao enviada.
